[phases.setup]
nixPkgs = ["unzip", "curl", "wget"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["reflex export --frontend-only"]

[start]
cmd = "reflex run --env prod --backend-port $PORT"
