[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python -m reflex export --frontend-only"]

[start]
cmd = "python -m reflex run --host 0.0.0.0 --port $PORT"
