[build]
builder = "NIXPACKS"

[deploy]
startCommand = "reflex run --env prod --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
