[build]
builder = "NIXPACKS"

[deploy]
startCommand = "reflex run --env prod --backend-port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { PORT = "8000" }
