[reflex]
# Configuraci贸n para el despliegue
app_name = "adeviento_web"
frontend_port = 3000
backend_port = 8000

# Configuraci贸n de build
export = true
export_dir = "web"

# Configuraci贸n de producci贸n
api_url = "https://your-app.vercel.app"
frontend_url = "https://your-app.vercel.app"
