[reflex]
# Configuraci贸n para el despliegue
app_name = "adeviento_web"
frontend_port = 3000
backend_port = 8000

# Configuraci贸n de build
export = true
export_dir = "web"

# Configuraci贸n de producci贸n
# Actualiza estas URLs con tu dominio real de Vercel
api_url = "https://adviento-viaje-shanghai.vercel.app"
frontend_url = "https://adviento-viaje-shanghai.vercel.app"
