services:
  - type: web
    name: adviento-shanghai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: reflex run --env prod --backend-host 0.0.0.0 --backend-port ${PORT:-10000} --frontend-port ${PORT:-10000} --no-frontend
    envVars:
      - key: REFLEX_ENV
        value: prod
      - key: ALLOWED_HOSTS
        value: "*"
