services:
  - type: web
    name: adviento-shanghai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: REFLEX_ENV
        value: prod
      - key: PORT
        value: 10000
